### ISSUE TITLE
给div添加索引的方法写的很好，很有帮助

### ISSUE THREAD

**Issue by gindepper** [hgnc-fe/ife-spring#2]

**Comment by consoles** [comment]
用了html5的data属性给元素增加了自定义属性，算是一种比较投机取巧的办法。另外task18的render函数中数组的遍历最好使用传统for循环，for-in循环最好遍历对象。为了避免字符串拼接使用了`[].join`，随着ES6的成熟，我们完全可以使用模板字符串！
